### PR TITLE
Saulius extend grammar

### PR DESCRIPTION
**Pull request by sauliusg**
It turned out that the original grammar did not permit expressions with the "NOT" token before braces (i.e. a "NOT (a < 1)" would be flagged as a syntax error). This is unusual for an expression grammar, and I suggest that this is fixed before release 1.0. The fix is very simple and proposed in this pull request.

### CODE REVIEW

**Comment by sauliusg** [comment]
I have realised that the filter-parser-yapp/FilterParser.yp is not updated accordingly, please wait for a filter-parser-yapp/FilterParser.yp update commit before merging...

**Review by merkys — APPROVED** [review]

**Comment by ltalirz** [comment]
@sauliusg Is this PR ready to be merged?
Let me know, and I can take care of resolving the conflict in .gitmodules

**Comment by sauliusg** [comment]
The PR is ready now. I have merged with the recent MaterialConsortia/API trunk, resolved the conflict and ran the tests. The tests concerning Filter grammar run (and the failing ones, for json-validator, should be resolved independently).

This PR fixes the intermediate state of the project where the grammar is fixed but is still in the API directory. We have decided to move the single authoritative grammar definition to the Filter syntax to the specification directory, OPTiMaDe. I am doing this change in another branch of mine; it will need a concerted changed in both OPTiMaDe and API repositories. Thus, I suggest merging the Filter grammar changes here at the moment, so that they do not get lost,

**Review by ltalirz — APPROVED** [review]
Happy to merge!

> We have decided to move the single authoritative grammar definition to the Filter syntax to the specification directory, OPTiMaDe

This seems reasonable to me (but will need approval of the other optimade people).
Also, do we then still split the API repository into tests/tools for the filter grammar and tests/tools for the json output?

**Comment by sauliusg** [comment]
> This seems reasonable to me (but will need approval of the other optimade people).

Sure!

> Also, do we then still split the API repository into tests/tools for the filter grammar and tests/tools for the json output?

My understanding is as follows:

- whatever documents are definitively provided in the documentation directory, OPTiMaDe, they MUST be tested there. So, for example, if we make change to the Filter grammar, we need to run tests to check if they are backwards compatible, otherwise we risk to break compatibility with previously working software. If we use semantic versioning (I strongly recommend this), we should keep backwards compatibility for minor and patch revisions.

- If we decide to provide JSON schema in the same documentation directory (OPTiMaDe), we should add schema tests here as well. There is not need to split any repos or directories for that; the tests will have different names ("Filter_999.\*" for filters, and something like "json-schema_999.\*" for schemas).

- if API needs to run tests against "official" grammars, it can do so as well. It will then use OPTiMaDe repository as a GIT submodule, and obtain necessary grammars from there; by no means should we have two copies of these documents. The submodules are already set up in my branches and I will offer them as my next PR set.

**Comment by ltalirz** [comment]
> whatever documents are definitively provided in the documentation directory, OPTiMaDe, they MUST be tested there.

I see. I agree it is an advantage to have the tests in the same repository, since this makes it simple to test any change to the document before making a commit.
On the other hand, I would also see an advantage in limiting traffic in the optimade repository by focusing on the specification only (not mixing it with the implementation of validators).
Anyhow, I'm ok with both solutions.

> There is not need to split any repos or directories for that

Same point here - if two pieces of code are independent (filter grammar+validators vs. json schema+validators), I usually find it helpful to split the codebase (#17 ).
It's not absolutely necessary of course.

**Pull request merged**
